### ISSUE TITLE
`NoClassDefFoundError` descriptions aren't remapped

### ISSUE THREAD

**Issue by altrisi** [natanfudge/Not-Enough-Crashes#31]
Those usually occur when calling something in a class that is client-side only. The same may happen for `NoSuchMethodError`, not tested.

Example: https://gist.github.com/SM9CC/da23ddf8c3a0edf57986ad96341c2d3d

```java
java.lang.NoClassDefFoundError: net/minecraft/class_4587
    at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.9)
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:3244)
    at java.lang.Class.getDeclaredMethod(Class.java:2551)
    ...
```

**Comment by natanfudge** [comment]
This is not a bug.
`net/minecraft/class_4587` is the true description of the exception. Changing it to anything else would disrupt the true meaning of the exception, and make it harder to find bugs. Furthermore, since this is just an exception description, remapping this would require a completely different system of parsing exception descriptions.
Finally, remapping `net/minecraft/class_4587` is not possible, obviously, since no such class exists. Imagine that error was " class not found: shober$##&#-+#+(#" , what would you remap it to?
