### ISSUE TITLE
Due to not having a license file, licensing is ambiguous.

### ISSUE THREAD

**Issue by Siuolplex** [natanfudge/Not-Enough-Crashes#66]
Hi, I noticed that this mod does not have a license file, and as such, according to most people I talked with, even though the mod says its MIT in its fabric.mod.json, its technically under ARR.

Note, Im not a lawyer, and I could easily be wrong. This is just what I have heard from people who know more about licensing than me. Either way, if you can, a license file would work great for this and would clear up the air and confusion.

**Comment by natanfudge** [comment]
Hey, thanks for bringing this up.
NEC is licensed under MIT. The license file was mistakenly removed when porting to Forge. 
I understand that this was ambigious, so I added a license file.

**Comment by nfitzen** [comment]
Licensing is generally ambiguous either way, since the `LICENSE` file doesn't apply for everything in the repository; for example, the Gradle wrapper is licensed under [`Apache-2.0`].

This is part of why people tell you to add a license header at the top of every file. (The other reason is that code is frequently copied in the world of free software.)

Some big-time projects like Linux have been using [SPDX IDs](https://spdx.org/ids/) for this purpose. As an example, the following could be added to the source code files:

```java
// SPDX-License-Identifier: MIT
// Copyright (C) 2021 Fudge and the NEC contributors
```

Also, does this project still use Too Many Crashes code? If so, you'd need to include [its copyright and license notice](https://github.com/Runemoro/TooManyCrashes/blob/master/LICENSE) as well, per the Expat license's condition. Furthermore, since others have contributed, their contributions would still be under "All Rights Reserved" if OP is correct. You'd need to contact them to rectify that.

(Obligatory "I'm not a lawyer, this is not legal advice" statement here.)

[`Apache-2.0`]: https://spdx.org/licenses/Apache-2.0.html

**Comment by natanfudge** [comment]
I'll re-add the original license.
As for contributions, the repository was always licensed under MIT, so their contributions will also be as such.
